### ISSUE TITLE
Controller buttons "sticking" when configuring.

### ISSUE THREAD

**Issue by AmbientMalice** [m64p/mupen64plus-GLideN64#12]
Basically, when I configure a controller, I select an option and press the relevant button on the controller. Then when I select the next option, the previously pressed button immediately applies to that option too. And only by pressing the same controller button again can I "unstick" it.

**Comment by loganmc10** [comment]
I haven't really experienced this but I'll try to look into it. I normally test with my keyboard so I don't play around in there much.

As an aside, I've heard a few grumblings about the controller setup screen, but no real specifics. What do you think I could do to make it more user friendly? The one thing I can think of is adding a "Bind All" button that would automatically go down the list one by one, instead of making the user click on each item to bind it, but anything else?

**Comment by AmbientMalice** [comment]
For a start, it ought to look like an actual GUI instead of a glorified INI editor. It doesn't even give keys. It gives 

![image](https://user-images.githubusercontent.com/10704701/30518094-18bfd37c-9bb7-11e7-97c6-e423f2ecbcfa.png)

I'm not saying you should copy N-Rage exactly, but look to it as a model for a relatively straightforward controller setup GUI.

![image](https://user-images.githubusercontent.com/10704701/30518109-8ff7afaa-9bb7-11e7-8301-67fddf8720a4.png)


Even the old Jabo controller plugin is fairly well laid out.

![image](https://user-images.githubusercontent.com/10704701/30518103-63c9db74-9bb7-11e7-9734-cc2809a80630.png)

The problem with the existing GUI is that it is barely abstracted from the underlying INI file. It is deeply alienating to typical end users.

Not to sound too critical, but this extends to other areas of the GUI, too.

This is... not good. It doesn't make effective use of space, and everything is referred to by ini values instead of human readable aliases.

![image](https://user-images.githubusercontent.com/10704701/30518117-e9976a6e-9bb7-11e7-8e41-37e292643e63.png)

However, I do appreciate the fundamental problem here -- because m64p plugins don't store GUI data in the plugin itself, there's no easy way to provide a properly working GUI that works across all possibly plugins.

**Comment by loganmc10** [comment]
Yeah I mean for the controller I can definitely have it convert the numeric keycode into a human readable format (I need to look into how different keyboard layouts are handled). For the rest of it, I did try to make it pretty "generic", there aren't special settings for each plugin.

It does give a little helper text if you hover over the item:
![image](https://user-images.githubusercontent.com/848146/30523992-ad01a4d4-9ba8-11e7-8e97-ff73e1b15bfb.png)

If I want to keep it generic/compatible with all plugins, that's really all the information I have to work with (the information in mupen64plus.cfg) I agree it's pretty ugly, but I'm not sure how to improve it without putting in all kinds of plugin specific code.

I agree the controller configuration could be a little prettier, but would it be more functional? I'm mostly concerned that people will be able to figure it out, and it already seems pretty straight-forward to me, except having some kind of a "Bind All" button, and probably having sliders for the deadzone/analog peak values.

**Comment by KingOfHyrule** [comment]
About the GUI, is it possible to make the information appear when you hover the mouse over the checkbox/value editor? I didn't really expected to see those boxes, and only found out about them by luck. Or maybe you could make an empty space where the information would show up, and write there something like "hover the mouse over the function to get a description". That would make it a little bit better and intuitive.

Also, I agree with the "looks like glorified INI editor" statement, but I also understand you can't do much due to the spec... And keeping it simple definitely isn't bad, but those functions aren't very intuitive to newcomers. Isn't there a way to, at least, make those functions names a bit less "raw"?
Making sliders instead of numbers (e.g. in the internal res config) would be better as well, but I'm not sure how much work that would take.

**Comment by loganmc10** [comment]
Yes I need to make the tooltips a little easier to find.

The problem is that the only information I have is what is in mupen64plus.cfg, using GLideN64's MSAA setting for example, this is what it looks like in the .cfg file:

```
# Enable/Disable MultiSampling (0=off, 2,4,8,16=quality)
MultiSampling = 0
```
So I use the stuff after the # as the "tooltip" info, I use "MultiSampling" as the item name. Besides that, the only thing I know is that the value is an integer, I don't know it's minimum or maximum value. If it's a boolean value I can make it a checkbox, and I can do a bit of sanity checking (if the value is an integer, I don't let them type letters or decimal values in that box for example), but the .cfg doesn't give me any other information unfortunately.

**Comment by KingOfHyrule** [comment]
I kind of imagined that this was the approach used. I can't really think of any way to making this better and agnostic without messing with the spec. Although, I doubt new plugins will show up, so maybe doing specific parameters for GlideN64 could be a good idea.

Can't you get a set number of integer parameters from the plugin? I mean, if GlideN64 reported that "MSAA" can be set to 2, 4, 8 or 16 (and just that), you could read that information and translate that to the GUI as a combo box or slider. And it would be pretty easy to maintain.

IDK, just throwing ideas around :)

**Comment by loganmc10** [comment]
> Can't you get a set number of integer parameters from the plugin? I mean, if GlideN64 reported that "MSAA" can be set to 2, 4, 8 or 16 (and just that), you could read that information and translate that to the GUI as a combo box or slider.

Yeah if the spec supported that it would be easy, but there is nothing in the cfg to tell me what valid values are available, the information after the # is just a comment, it could say anything.

With regards to the original issue @AmbientMalice I've now tested this on Windows and Linux with 2 different controllers (Xbox One controller and Ipega controller), I can't reproduce the sticking. Do you have any more details? Does it happen all the time? Is the controller USB or bluetooth? etc

**Comment by AmbientMalice** [comment]
I haven't been able to reproduce the issue recently. I'll close this issue and reopen if it reoccurs, and hopefully I'll have a better idea of how to reliably reproduce it.
