### ISSUE TITLE
which qt5 packages are rquired?

### ISSUE THREAD

**Issue by pcuinty** [m64p/mupen64plus-GLideN64#40]
I get an error

````
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: version `Qt_5' not found (required by ./mupen64plus-gui)
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5: version `Qt_5' not found (required by ./mupen64plus-gui)
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.7' not found (required by ./mupen64plus-gui)
./mupen64plus-gui: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5' not found (required by ./mupen64plus-gui)
````

I installed ``qt5-default`` still get this error

**Comment by loganmc10** [comment]
The version on the website is built on Debian Stretch, which uses Qt 5.7

What OS/distro are you trying this on?

**Comment by pcuinty** [comment]
ubuntu 16.04

**Comment by loganmc10** [comment]
16.04 comes with 5.9 so that shouldn't be an issue.

It's hard for me to say, I'm not sure what might be wrong. I've tested it on Ubuntu 16.04 and Fedora myself and didn't run into any issues.

I assume something is wrong with your Qt installation, or you somehow have multiple version of Qt installed or something

**Comment by loganmc10** [comment]
> That's probably the issue, right?

Yes that Qt version is the issue, but 16.04 should have a more recent version of Qt

**Comment by loganmc10** [comment]
Sorry I just realized that Ubuntu 16.04 does come with Qt 5.5 but I'm building on Debian Stretch which uses 5.7, I'll need to figure something out
