### ISSUE TITLE
Include command-line executable?

### ISSUE THREAD

**Issue by phrone** [m64p/mupen64plus-GLideN64#46]
Your bundle is excellent, but would it be possible to include the command-line version as well? It works much better with tools like LaunchBox.

**Comment by loganmc10** [comment]
> It works much better with tools like LaunchBox.

In what way? What functionally is mupen64plus-gui missing?

**Comment by phrone** [comment]
It might not be missing anything, but command-line executables are preferable as you can hand over the control to LaunchBox directly. It would help if the GUI supports the following features:
- Ability to specify which game to load, as an executable parameter
- Ability to specify whether to start in full screen mode, as an executable parameter
- Ability to exit the program when you exit the ROM, as an executable parameter or a setting (Dolphin has such a feature)
- Ability to start a ROM in silent mode without showing the GUI window (if possible)

**Comment by loganmc10** [comment]
Sorry it's not very well documented but that is all pretty much possible:

mupen64plus-gui.exe --nogui /path/to/rom.n64

the --nogui option will remove the GUI elements, it will also close the application when the ROM closes.

For fullscreen, there is a setting under "Video-General" that will control whether the game launches in fullscreen or not. There isn't a command line way to set this, since it's actually a configuration setting that is stored in mupen64plus.cfg. I believe mupen64plus-ui-console has a command line option for --fullscreen, but it actually just temporarily modifies the option in mupen64plus.cfg and sets it back when the game closes. I could potentially add a similar feature, but it seems a little "hacky", I'd rather just leave the config option.

**Comment by phrone** [comment]
Awesome! Thanks for the information. This will definitely help others who want to do the same thing as me. Well, until proper documentation comes out. Thank you very much, @loganmc10.
