### ISSUE TITLE
Latest build not working on either win32 or win64

### ISSUE THREAD

**Issue by OtavioRaposo** [m64p/mupen64plus-GLideN64#58]
I've downloaded the latest build of m64p (Feb 28/2018) and the games won't start. When I choose the game via "Open ROM", the game simply doesn't load. Also, when I try to select my USB Joystick in the Controller menu with the Automatic option enabled, the emulator selects the option "None".

**Comment by loganmc10** [comment]
I can't reproduce the issues you are having with "Open ROM", it works for me, after you try to open a ROM, can you go to:

Emulation->View Log, and post the log here, it may have some clue as to why the game isn't starting.

As for your controller, it's probably doing that because it can't automatically configure your controller. Again, if you try to select the controller, and then go to "Emulation->View Log", you will probably see lines like this:

```
Input Error: No auto-config found for joystick named 'Android Controller Gen-2(ACC)' in InputAutoConfig.ini
```

That is what happens when I try my Android controller.

If you change the mode to "manual" and then select your controller, it should work. You'll then need to manually bind each key (there is a "Bind All" button which will walk through them 1 by 1)
