### ISSUE TITLE
GlideN64 Won't Show FPS, VIS, Percent, or Others

### ISSUE THREAD

**Issue by pdrome** [m64p/mupen64plus-GLideN64#62]
I'm using the March 10th, 2018 version and these options in the GlideN64 plugin no longer seem to work.

I am uncertain if this in an m64p issue or a gliden64 issue.  What would be the best way to test this running linux?  m64py?

**Comment by Jj0YzL5nvJ** [comment]
I can confirm this behaviour on Xubuntu 16.04.4 LTS x64, bisected to gonetz/GLideN64@30f56c98bd62b5d3d12bcb5109d05a211f1fc9d1

The routes are wrong:
```
$ cd /usr/share/fonts/
$ find * | grep LiberationMono-Regular.ttf
truetype/liberation/LiberationMono-Regular.ttf
truetype/liberation2/LiberationMono-Regular.ttf
$ find * | grep FreeSans.ttf
truetype/freefont/FreeSans.ttf
```

**Comment by loganmc10** [comment]
Yeah this would be an issue to file with GLideN64. I'm not a freetype expert but it seems they different distros store the fonts in different paths, so it might be difficult to solve. There might be a better way to find the font rather than a hard coded path. Or perhaps GLideN64 could include a free/opensource .ttf file with it and not rely on what may or may not be included with the OS

**Comment by pdrome** [comment]
I moved this over to GlideN64.  Closing this issue.
