### ISSUE TITLE
Very low performance with angrylion-plus compared to PJ64

### ISSUE THREAD

**Issue by Jj0YzL5nvJ** [m64p/mupen64plus-GLideN64#63]
I've been doing some tests compiling projects in Visual Studio Community 2015.3. Among them are angrylion's RDP Plus and Project64 ...so I did a little test comparing GLideN64 and angrylion's RDP Plus in both m64p and Project64.
 GLideN64 is a little bit faster in m64p, but on the other hand, angrylion-plus is abysmally faster in PJ64. It's so fast that I think there must be some bottleneck in some m64p component (rsp-cxd4-sse2?).
 The both emulators use almost the same resources, but m64p is lagging at 800 x 600 and Project64 at 1280 x 960 is always at 60 VI's and very fluid.
 I can provide the binaries if @loganmc10 wants.
[angrylion-plus_r7-dirty-6af5b4c](https://github.com/ata4/angrylion-rdp-plus/issues/29#issuecomment-373653727)

I don't think it's right to put the PJ64 (v2.4.0-668-gc506db57) binaries here ...an email or something? installer or portable?

Edit:
P.S: I have not tried with version 2.3.2 but it's probably the same story.

**Comment by loganmc10** [comment]
Yes the problem is rsp-cxd4. Project64 has a recompiler in their RSP (think dynarec vs interpreter in the emulator core). Rsp-cxd4 is only an interpreter.

Project64's RSP could be ported to mupen64plus, probably without too much difficulty, but it's recompiler is x86 only, no x64 or arm, so there has been limited interest

**Comment by TheLocoBandito** [comment]
x86 is on it's last legs in my book and there is no reason to invest time in that for new development.

I'm not against 32-bit applications in general and I'm quite dependent on a couple of 32-bit applications still, but 32-bit OS is where I draw the line completely.

Frankly x86 just needs to die and should have been buried with Windows XP.

Anyway, as @loganmc10 says it's because of Project64/Zilmar's RSP angrylion-rdp-plus runs so fast.

Try using this in Project64 and you should see same performance as with Mupen64Plus cxd4

[cxd4 rsp (Project64).zip](https://github.com/m64p/mupen64plus-GLideN64/files/1823749/cxd4.rsp.Project64.zip)

Whether or not it's worthwhile to port Zilmar's RSP to Mupen64Plus it's up to Logan to decide but on my end I see only mild performance gains with Zilmar's RSP, cxd4 isn't that slow on good hardware.

But if the demand for Zilmar's RSP is high, I see no reason not to port it.

**Comment by pdrome** [comment]
The parallel n64 guys did some experiments using LLVM to recompile the cxd4 RSP plugin.  Not sure if it is applicable, but it might be a path forward which would work with other architectures and speed things up:

https://www.libretro.com/index.php/parallel-rdp-and-rsp-updates-september-2016/

**Comment by TheLocoBandito** [comment]
@Jj0YzL5nvJ 

Had any chance to try cxd4 with Project64?

**Comment by Jj0YzL5nvJ** [comment]
It crash with PJ64 v2.4.0-668-gc506db57. I don't have my own Windows installation, so I can only try it on a few chances in my workplace.
 I can try on v2.3.2 later.

**Comment by dbyzin** [comment]
Hi Jj0YzL5nvJ, can you please share with me your "PJ64" with the angrylion? I wanna see if it runs really faster here too. Please send it on my email: rafaeldby@gmail.com or give me an link! Thank you very much!

**Comment by Jj0YzL5nvJ** [comment]
Good news for @dbyzin and any pedestrians, today my levels of dopamine don't are in "negative levels". In short, I'm a little sociable today (aberrant status ailments).
 Search for "Is PJ64 dead?" in the NGEmu forums. A little gift award you.
