### ISSUE TITLE
"Couldn't load core library, please set the path in settings."

### ISSUE THREAD

**Issue by brushtool** [m64p/mupen64plus-GLideN64#97]
Happens when trying to open a game, or changing plugin settings.
Upon further inspection, it appears that it can't locate "libminizip.so.1".
`
GUI Error: dlopen('/home/x/mupen64plus/libmupen64plus.so.2') failed: libminizip.so.1: cannot open shared object file: No such file or directory
GUI Error: AttachCoreLib() Error: failed to find Mupen64Plus Core library
`
Thanks

**Comment by loganmc10** [comment]
Minizip is a dependency, you need to install it via your package manager (apt or yum or whatever it may be)

**Comment by brushtool** [comment]
> Minizip is a dependency, you need to install it via your package manager (apt or yum or whatever it may be)

Thank you, that worked!

**Comment by bigboo3000** [comment]
Hi I'm trying to test m64p on a libreelec 9 x86-64 build, I have the same issue because minizip is not included in Libreelec, only zlib.

Would it be possible to use zlib instead of minizip to make it work on libreelec?

https://forum.libreelec.tv/thread/12662-libreelec-9-0-reborn-remix-emulationstation-retroarch-dolphinqt-moonlight-chrome/?postID=102914#post102914

**Comment by loganmc10** [comment]
The binary package that I distribute on m64p.github.io is built on Ubuntu. Essentially Ubuntu is the only officially supported distro for the binary package, although you may get lucky with other distributions.


mupen64plus supports building without minizip, and if you built m64p from source on some other distro it should work. (you would need to clone this repo and build using the ```build.sh``` script).
